### PR TITLE
e-learning integration

### PR DESCRIPTION
**Pull request by EHJ-52n**

### CODE REVIEW

**Comment by EHJ-52n** [comment]
@andreaiervolino 

Could you please update the contrib modules to the latest version except these two:
- Harmony Access    `7.x-1.0-alpha1`
- Harmony Core  `7.x-1.0-alpha9`

They should have these versions.

In addition, please consider the new layout and navbar which does not have any e-learning menu entry. The landing point will still be:

> https://wie.dev.52north.org/en/e-learning

e-learning-landing-page

Please do not change the `.gitignore` file. It seems that you have reset it to its default value.

**Comment by EHJ-52n** [comment]
@andreaiervolino 

I were able to test your pullrequest and find the following issues:
1. the WaterInnEU deploy module seems not to install/activate any required module. Maybe, you need to merge all the update hook implementations in a new one!? I activated the following modules by hand:
   - Course object E-learning WaterinnEU (course_object_e_learning_waterinneu)
   -  Main menu elearning waterinneu (main_menu_elearning_waterinneu)
   - Permissions E-learning WaterinnEU (permissions_e_learning_waterinneu)
   - Roles E-learning WaterinnEU (roles_e_learning_waterinneu)
   - Views E-learning WaterinnEU (views_elearning_waterinneu)
   - Waterinneu content type randbee (waterinneu_content_type_randbee)
   - waterinneu_taxonomy_randbee
2. You should **not** add any entry to the main menu. It should be only:
   `Home | Products | Organisations | Matchmaking & Support | Success Stories`
3. When accessing `http://localhost/drupal/en/e-learning`, I get an empty drupal page.
   ^ resulting from no e-learning content in the system. What about adding some text here introducing the system/feature.
4. Please rename the feature group to something more useful than "feature", e.g. "WaterInnEU - e-learning".
5. Do you need the "UUID Services Example" feature?
   
   > Example feature of a UUID service. Works well with the Deploy Example feature as a client.
   > Unmet dependencies: rest_server (Missing), services (Missing)

**Comment by EHJ-52n** [comment]
@andreaiervolino 

We are already using `print_pdf_wkhtmltopdf`. Hence, I am unsure if we need `print_pdf_dompdf`.

Is the e-learning implementation directly depending on `dompdf`?

**Comment by andreaiervolino** [comment]
print_pdf_dompdf is the library that I used to print certificate. E-learning implementation should not work properly without it.

**Comment by EHJ-52n** [comment]
Should the `print` module abstract from the used library? Hence, I expect that the system is able to print certificates with `wkhtml2pdf`, too!?

What do you think?

**Comment by andreaiervolino** [comment]
It should be able to do that. Let's try.

**Comment by EHJ-52n** [comment]
@andreaiervolino 

I think you still need to remove the `dompdf` implementation for the `print` module before I can merge this.

**Comment by EHJ-52n** [comment]
Branch is manually merged in 62fcda904abbb60c56497ed8e7c493d3498cceff.

**Pull request closed without merging**
